# Generated by Django 4.2.1 on 2023-05-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_pos',
            name='job_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
